### ISSUE TITLE
Publish toastr 2.1.3 to npm

### ISSUE THREAD

**Issue by BBosman** [CodeSeven/toastr#450]
`npm info toastr version` gives `2.1.2`.

Could 2.1.3 be published to npm?

**Comment by MarkHerhold** [comment]
Ping @TimFerrell

**Comment by wcphart** [comment]
I would also appreciate this. Spent a bit of time reading through open and closed issues trying to figure out why closeOnHover was not working, then noticed the version difference (I know I should have spotted that first but... oh well)
 
Its been 4 months. @TimFerrell

**Comment by burtyish** [comment]
RTL support is a deal breaker for the project I'm working on, so I was happy to find that RTL was added in `2.1.3`. You can imagine how disappointing it was to find out that version `2.1.3` hasn't been published to npm even though this issue was reported such a long time ago.
If you simply _must_ get the latest version via npm, you can reference the git tag directly in your `package.json` like this:
```json
"toastr": "CodeSeven/toastr#2.1.3"
```

**Comment by larvanitis** [comment]
Yes please.

You can also add it to `package.json` like this (tarball download vs git):
```
"toastr": "https://github.com/CodeSeven/toastr/archive/2.1.3.tar.gz"
```

**Comment by pawelgorka** [comment]
+1

**Comment by jelen07** [comment]
How it looks nowadays @TimFerrell?

**Comment by obinnangini** [comment]
Is there any update on when the latest version will be published to NPM? @TimFerrell @johnpapa @hfjallemark

**Comment by xemasiv** [comment]
Any updates on this? Anyone maintaining a forked branch?

**Comment by hfjallemark** [comment]
Maybe need to start looking for a new maintainer for this project (I haven't used nor been active in this repo for a couple of years). @TimFerrell @johnpapa what do you guys think?

**Comment by TimFerrell** [comment]
I’m OK with finding another maintainer. For the record, the problem with 2.1.3 and npm is that it was published with the incorrect files, and then rolled back. Once the original files were packaged and ready, npm rejected the update because you can’t redeploy a version. So we need 2.1.4 either in the same exact state as 2.1.3 or add something else to justify the rev.

**Comment by JLHwung** [comment]
We have forked toastr on https://github.com/easyops-cn/toastr and fixes some travis-ci issues https://travis-ci.org/easyops-cn/toastr/builds/232680052. The forked package is published as `@easyops/toastr^2.1.3` since we thought the project is unmaintained.

I can help maintaining toastr as we use it in production environment.

**Comment by hfjallemark** [comment]
@TimFerrell @johnpapa what do you say about making @JLHwung a maintainer of this repo and get his fork merged back?

**Comment by TimFerrell** [comment]
@hfjallemark I'm OK with it. Can we get a PR from his fork into ours so we can get the diffs first?

**Comment by JLHwung** [comment]
The forked https://github.com/easyops-cn/toastr is done with some opinionated changes:
- use yarn lock file
- test every branch on travis
- use phantomjs-prebuilt

Although it fixes some testing issues, if one would draft a PR on this fork, we might need to discuss these changes and cherry pick corresponding commits.

**Comment by hfjallemark** [comment]
@JLHwung can you open up a PR?

**Comment by danosaure** [comment]
I would suggest to just republish with a new version and move on?

**Comment by TimFerrell** [comment]
Tag `2.1.4` has just been published to NPM . It is exactly the same as `2.1.3`.
