### ISSUE TITLE
Error 404 for https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js 

### ISSUE THREAD

**Issue by ninio** [CodeSeven/toastr#453]
The minified JS is no logner present from the following path:
https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js

However the unminified is still present:
https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.js

**Comment by ninio** [comment]
I see it's present from the following path
https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js

But this still might break someones code due to this change.

**Comment by TimFerrell** [comment]
I've created https://github.com/cdnjs/cdnjs/issues/8779 in CDNJS repo to track the issue.
I will update thread with details.

**Comment by PeterDaveHello** [comment]
CDNJS maintainer here, I'm sorry about this accidently appeared breaking change, please allow me to explain the reason and discuss about the solution.

Actually, the policy of CDNJS, is not to support the "latest" usage, since there may be cache control issue on that usage, and will make the hosting process much more complex, however, the PR cdnjs/cdnjs#1500 was merged, and now there is a breaking change.

Aonther reason is that we are now using auto-update mechanism for most of the libraries, there are now 2.4k libraries hosted on CDNJS, it's impossible to manually update the libraries anymore, by using auto-update mechanism, we will/can only use the same directory/file structure from upstream, the css/js file in toastr before v2.1.0 is manually put in individual js and css directory, however, there is no directory under the build folder, so once the auto-update applied, the `css/` and `js/` disappeared in the url, I'm sorry about that.

Now I wondering if we could 

1. just "fix" the url structure, but just keep the "latest" stuck on "v2.1.3", do not update it anymore, just for fixing/preventing the breaking changes, no more updates, since we can not always manually maintain that structure, unless, authors of toastr will like to send PRs on every toastr release.

2. one another thought is to add the css and js folder in the build folder in toastr repo, and manually "fix" the url structure for toastr v2.1.1~2.1.3 on CDNJS(but also keep the files without the css/js folders), since the structures will be the same, so I may also update the "lastet" link to the real latest one sometimes(I can not gaurantee that, for the same reason).

Do you guys have any suggestions? Many thanks.

**Comment by tixastronauta** [comment]
@PeterDaveHello Thanks for taking your time to explain! I'd go the solution **1** and add some explanation comment on the first line of the CSS and JS files.

**Comment by TimFerrell** [comment]
Thanks for the detailed reply.
Let's move forward with the first option, please.

**Comment by PeterDaveHello** [comment]
Sure be fine now, thank you guys.
