### ISSUE TITLE
insert custom css class

### ISSUE THREAD

**Issue by sido420** [CodeSeven/toastr#555]
Is it possible to specify a custom CSS class to be included in toast's element?

this will let you change the style of individual toasts messages?

Alternatively, is it possible to create new notification types other than error, info, warning etc.?

**Comment by john-sanders-2** [comment]
You can change the icon class by overriding the `iconClass` [option](https://github.com/CodeSeven/toastr/blob/61c48a6bbdfe1bd883c40110797b2e0cf3800102/toastr.js#L180).

For example:
```
toastr.info("message",` "title", { iconClass: 'your-icon-class' });
```

The icon class is added to each individual toast, and controls the color and icon that is displayed. You can use it to override other toastr styles as well since it's on the individual toast container element.

As for extending toastr with new toast types, the code is not extensible in that way. The toastr code returns a plain object as its public interface, with all of it's internals hidden.

Recommendations I've seen in the past are to fork the library, and add your own toast types, then use your forked library.

**Comment by sido420** [comment]
iconClass didn't work. 

I think it gets overriden by the .info/.error etc [methods](https://github.com/CodeSeven/toastr/blob/61c48a6bbdfe1bd883c40110797b2e0cf3800102/toastr.js#L71).

Any thoughts?

**Comment by john-sanders-2** [comment]
Can you provide code examples (JS & CSS)? The code sample I provided was tested and worked for me.

**Comment by sido420** [comment]
I assign options eg. { iconClass: 'your-icon-class' } to the toastr.options property then call .info or .success on toastr object.

**Comment by sido420** [comment]
Using options in .info() call directly seems to work. 

However, I noticed another issue, if another toast (say 't') is also being displayed at the same time then it changes t's position and once t is removed (either thru tapping or timeout), then any new toasts using iconClass do not show at all after that.

Is this a known issue? I've changed my code to avoid using toast.options and pass options in method calls directly.

**Comment by sido420** [comment]
looks like I may have hit 438 which is resolved in 2.1.4 (unavailable thru bower so created 556).

**Comment by john-sanders-2** [comment]
I highly encourage you to comment with actual code examples instead of trying to describe your problem. 

If you're using `toastr.options` to set options, then you need to override the `iconClasses` option. Overriding `iconClass` only seems to work if you pass it into your `toastr.info()` function call, as I did above in my example.

Check out this pen for an example: [https://codepen.io/johnsanders2/pen/LeGGja](https://codepen.io/johnsanders2/pen/LeGGja)

In this particular example, I just added a "notice" class for info toasts, but you can replace it altogether if you need.

**Comment by sido420** [comment]
Thanks for the explanation and solving the problem for me @john-sanders-2.

**Comment by sido420** [comment]
And, I will try to come up with code examples next time. Thanks for the suggestion.
